name: expense_tracker
description: "簡單好用的記帳 App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.2
  path: ^1.9.0
  intl: ^0.19.0
  fl_chart: ^0.69.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
